/**
 * generated by Xtext 2.12.0
 */
package brew.xtext.brew;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see brew.xtext.brew.BrewPackage
 * @generated
 */
public interface BrewFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  BrewFactory eINSTANCE = brew.xtext.brew.impl.BrewFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Root</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Root</em>'.
   * @generated
   */
  BrewRoot createBrewRoot();

  /**
   * Returns a new object of class '<em>Ale Import</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Ale Import</em>'.
   * @generated
   */
  AleImport createAleImport();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  BrewPackage getBrewPackage();

} //BrewFactory
