/**
 * generated by Xtext 2.12.0
 */
package brew.xtext.brew;

import ale.xtext.ale.AbstractMethod;
import ale.xtext.ale.ConcreteMethod;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Method Bind</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link brew.xtext.brew.MethodBind#getAbstractMethod <em>Abstract Method</em>}</li>
 *   <li>{@link brew.xtext.brew.MethodBind#getConcreteMethod <em>Concrete Method</em>}</li>
 * </ul>
 *
 * @see brew.xtext.brew.BrewPackage#getMethodBind()
 * @model
 * @generated
 */
public interface MethodBind extends EObject
{
  /**
   * Returns the value of the '<em><b>Abstract Method</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Abstract Method</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Abstract Method</em>' reference.
   * @see #setAbstractMethod(AbstractMethod)
   * @see brew.xtext.brew.BrewPackage#getMethodBind_AbstractMethod()
   * @model
   * @generated
   */
  AbstractMethod getAbstractMethod();

  /**
   * Sets the value of the '{@link brew.xtext.brew.MethodBind#getAbstractMethod <em>Abstract Method</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Abstract Method</em>' reference.
   * @see #getAbstractMethod()
   * @generated
   */
  void setAbstractMethod(AbstractMethod value);

  /**
   * Returns the value of the '<em><b>Concrete Method</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Concrete Method</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Concrete Method</em>' reference.
   * @see #setConcreteMethod(ConcreteMethod)
   * @see brew.xtext.brew.BrewPackage#getMethodBind_ConcreteMethod()
   * @model
   * @generated
   */
  ConcreteMethod getConcreteMethod();

  /**
   * Sets the value of the '{@link brew.xtext.brew.MethodBind#getConcreteMethod <em>Concrete Method</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Concrete Method</em>' reference.
   * @see #getConcreteMethod()
   * @generated
   */
  void setConcreteMethod(ConcreteMethod value);

} // MethodBind
