/**
 * generated by Xtext 2.12.0
 */
package brew.xtext.brew;

import org.eclipse.emf.ecore.EObject;

import org.eclipse.xtext.common.types.JvmFormalParameter;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Param Converter</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link brew.xtext.brew.ParamConverter#getParamName <em>Param Name</em>}</li>
 *   <li>{@link brew.xtext.brew.ParamConverter#getConverter <em>Converter</em>}</li>
 *   <li>{@link brew.xtext.brew.ParamConverter#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see brew.xtext.brew.BrewPackage#getParamConverter()
 * @model
 * @generated
 */
public interface ParamConverter extends EObject
{
  /**
   * Returns the value of the '<em><b>Param Name</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Param Name</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Param Name</em>' reference.
   * @see #setParamName(JvmFormalParameter)
   * @see brew.xtext.brew.BrewPackage#getParamConverter_ParamName()
   * @model
   * @generated
   */
  JvmFormalParameter getParamName();

  /**
   * Sets the value of the '{@link brew.xtext.brew.ParamConverter#getParamName <em>Param Name</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Param Name</em>' reference.
   * @see #getParamName()
   * @generated
   */
  void setParamName(JvmFormalParameter value);

  /**
   * Returns the value of the '<em><b>Converter</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Converter</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Converter</em>' reference.
   * @see #setConverter(BasicConverter)
   * @see brew.xtext.brew.BrewPackage#getParamConverter_Converter()
   * @model
   * @generated
   */
  BasicConverter getConverter();

  /**
   * Sets the value of the '{@link brew.xtext.brew.ParamConverter#getConverter <em>Converter</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Converter</em>' reference.
   * @see #getConverter()
   * @generated
   */
  void setConverter(BasicConverter value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see brew.xtext.brew.BrewPackage#getParamConverter_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link brew.xtext.brew.ParamConverter#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

} // ParamConverter
