/*
 * generated by Xtext 2.12.0
 */
package iot.lua.xtext


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class IotLuaXtextStandaloneSetup extends IotLuaXtextStandaloneSetupGenerated {

	def static void doSetup() {
		new IotLuaXtextStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
