/*
 * generated by Xtext 2.12.0
 */
package iot.lua.xtext


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class IotLuaXtextRuntimeModule extends AbstractIotLuaXtextRuntimeModule {
}
