<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="prodSysTokenHolder" nsURI="http://prodSysTokenHolder" nsPrefix="prodSysTokenHolder">
  <eClassifiers xsi:type="ecore:EClass" name="HBindConveyor" eSuperTypes="../../TokenHolder/model/tokenHolder.ecore#//H">
    <eStructuralFeatures xsi:type="ecore:EReference" name="delegate" lowerBound="1"
        eType="ecore:EClass ../../ProdSys/model/prodSys.ecore#//Conveyor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RBindRoot" eSuperTypes="../../TokenHolder/model/tokenHolder.ecore#//R">
    <eStructuralFeatures xsi:type="ecore:EReference" name="delegate" lowerBound="1"
        eType="ecore:EClass ../../ProdSys/model/prodSys.ecore#//Root"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PBindMachine" eSuperTypes="../../TokenHolder/model/tokenHolder.ecore#//P">
    <eStructuralFeatures xsi:type="ecore:EReference" name="delegate" lowerBound="1"
        eType="ecore:EClass ../../ProdSys/model/prodSys.ecore#//Machine"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TBindPart" eSuperTypes="../../TokenHolder/model/tokenHolder.ecore#//T">
    <eStructuralFeatures xsi:type="ecore:EReference" name="delegate" lowerBound="1"
        eType="ecore:EClass ../../ProdSys/model/prodSys.ecore#//Part"/>
  </eClassifiers>
</ecore:EPackage>
