/*
 * generated by Xtext 2.12.0
 */
package iot.simpleexpressions.xtext.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class IoTAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("iot/simpleexpressions/xtext/parser/antlr/internal/InternalIoT.tokens");
	}
}
