/**
 * generated by Xtext 2.10.0
 */
package ale.xtext.ale.impl;

import ale.xtext.ale.AleClass;
import ale.xtext.ale.AlePackage;
import ale.xtext.ale.ImportAle;
import ale.xtext.ale.ImportEcore;
import ale.xtext.ale.Root;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Root</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link ale.xtext.ale.impl.RootImpl#getName <em>Name</em>}</li>
 *   <li>{@link ale.xtext.ale.impl.RootImpl#getImportEcore <em>Import Ecore</em>}</li>
 *   <li>{@link ale.xtext.ale.impl.RootImpl#getImportsAle <em>Imports Ale</em>}</li>
 *   <li>{@link ale.xtext.ale.impl.RootImpl#getClasses <em>Classes</em>}</li>
 * </ul>
 *
 * @generated
 */
public class RootImpl extends MinimalEObjectImpl.Container implements Root
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getImportEcore() <em>Import Ecore</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getImportEcore()
   * @generated
   * @ordered
   */
  protected ImportEcore importEcore;

  /**
   * The cached value of the '{@link #getImportsAle() <em>Imports Ale</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getImportsAle()
   * @generated
   * @ordered
   */
  protected EList<ImportAle> importsAle;

  /**
   * The cached value of the '{@link #getClasses() <em>Classes</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getClasses()
   * @generated
   * @ordered
   */
  protected EList<AleClass> classes;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RootImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AlePackage.Literals.ROOT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AlePackage.ROOT__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ImportEcore getImportEcore()
  {
    return importEcore;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetImportEcore(ImportEcore newImportEcore, NotificationChain msgs)
  {
    ImportEcore oldImportEcore = importEcore;
    importEcore = newImportEcore;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, AlePackage.ROOT__IMPORT_ECORE, oldImportEcore, newImportEcore);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setImportEcore(ImportEcore newImportEcore)
  {
    if (newImportEcore != importEcore)
    {
      NotificationChain msgs = null;
      if (importEcore != null)
        msgs = ((InternalEObject)importEcore).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - AlePackage.ROOT__IMPORT_ECORE, null, msgs);
      if (newImportEcore != null)
        msgs = ((InternalEObject)newImportEcore).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - AlePackage.ROOT__IMPORT_ECORE, null, msgs);
      msgs = basicSetImportEcore(newImportEcore, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AlePackage.ROOT__IMPORT_ECORE, newImportEcore, newImportEcore));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<ImportAle> getImportsAle()
  {
    if (importsAle == null)
    {
      importsAle = new EObjectContainmentEList<ImportAle>(ImportAle.class, this, AlePackage.ROOT__IMPORTS_ALE);
    }
    return importsAle;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<AleClass> getClasses()
  {
    if (classes == null)
    {
      classes = new EObjectContainmentEList<AleClass>(AleClass.class, this, AlePackage.ROOT__CLASSES);
    }
    return classes;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case AlePackage.ROOT__IMPORT_ECORE:
        return basicSetImportEcore(null, msgs);
      case AlePackage.ROOT__IMPORTS_ALE:
        return ((InternalEList<?>)getImportsAle()).basicRemove(otherEnd, msgs);
      case AlePackage.ROOT__CLASSES:
        return ((InternalEList<?>)getClasses()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case AlePackage.ROOT__NAME:
        return getName();
      case AlePackage.ROOT__IMPORT_ECORE:
        return getImportEcore();
      case AlePackage.ROOT__IMPORTS_ALE:
        return getImportsAle();
      case AlePackage.ROOT__CLASSES:
        return getClasses();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case AlePackage.ROOT__NAME:
        setName((String)newValue);
        return;
      case AlePackage.ROOT__IMPORT_ECORE:
        setImportEcore((ImportEcore)newValue);
        return;
      case AlePackage.ROOT__IMPORTS_ALE:
        getImportsAle().clear();
        getImportsAle().addAll((Collection<? extends ImportAle>)newValue);
        return;
      case AlePackage.ROOT__CLASSES:
        getClasses().clear();
        getClasses().addAll((Collection<? extends AleClass>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case AlePackage.ROOT__NAME:
        setName(NAME_EDEFAULT);
        return;
      case AlePackage.ROOT__IMPORT_ECORE:
        setImportEcore((ImportEcore)null);
        return;
      case AlePackage.ROOT__IMPORTS_ALE:
        getImportsAle().clear();
        return;
      case AlePackage.ROOT__CLASSES:
        getClasses().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case AlePackage.ROOT__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case AlePackage.ROOT__IMPORT_ECORE:
        return importEcore != null;
      case AlePackage.ROOT__IMPORTS_ALE:
        return importsAle != null && !importsAle.isEmpty();
      case AlePackage.ROOT__CLASSES:
        return classes != null && !classes.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //RootImpl
