<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="iot" nsURI="http://www.example.org/iot" nsPrefix="iot">
  <eClassifiers xsi:type="ecore:EClass" name="IotOperationDef" abstract="true" interface="true">
    <eAnnotations source="@Required"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HWComp" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="services" upperBound="-1"
        eType="#//IotOperationDef" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sensor" eSuperTypes="#//HWComp"/>
  <eClassifiers xsi:type="ecore:EClass" name="Actuator" eSuperTypes="#//HWComp"/>
  <eClassifiers xsi:type="ecore:EClass" name="System">
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
        eType="#//HWComp" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="boards" upperBound="-1"
        eType="#//Board" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sketch" eType="#//Sketch"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Board">
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
        eType="#//HWComp"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//BoardType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sketch">
    <eStructuralFeatures xsi:type="ecore:EReference" name="activity" eType="#//IotActivity"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IotActivity" abstract="true" interface="true">
    <eAnnotations source="@Required"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BoardType">
    <eLiterals name="RaspberryPi"/>
    <eLiterals name="Arduino" value="1"/>
    <eLiterals name="BeagleBoard" value="2"/>
  </eClassifiers>
</ecore:EPackage>
