cp -r fsm fsm_guarded_lua
cp -r fsm fsm_guarded_simpleexp
cp -r fsm fsm_guarded_hierarchical_lua
cp -r fsm actionlanguage_fsm_guarded_lua
cp -r fsm fsm_guarded_hierarchical_simpleexp
cp -r fsm actionlanguage_fsm_guarded_simpleexp
cp -r fsm actionlanguage_effectful_fsm_guarded_lua
cp -r fsm actionlanguage_fsm_guarded_hierarchical_lua
cp -r fsm actionlanguage_effectful_fsm_guarded_simpleexp
cp -r fsm actionlanguage_fsm_guarded_hierarchical_simpleexp
cp -r fsm actionlanguage_effectful_fsm_guarded_hierarchical_lua
cp -r fsm actionlanguage_effectful_fsm_guarded_hierarchical_simpleexp
