/*
 * generated by Xtext 2.12.0
 */
package ale.xtext.tests

import ale.xtext.ale.AlePackage
import ale.xtext.ale.AleRoot
import ale.xtext.validation.AleValidator
import com.google.inject.Inject
import org.eclipse.emf.codegen.ecore.genmodel.GenModelPackage
import org.eclipse.emf.ecore.EPackage
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.eclipse.xtext.testing.validation.ValidationTestHelper
import org.eclipse.xtext.util.JavaVersion
import org.eclipse.xtext.xbase.testing.CompilationTestHelper
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(AleInjectorProvider)
class AleTests {
	@Inject extension ParseHelper<AleRoot>
	@Inject extension CompilationTestHelper compilationHelper
	@Inject extension ValidationTestHelper
	
	@Before
	def void setUp() {
		EPackage.Registry.INSTANCE.put(GenModelPackage.eNS_URI, GenModelPackage.eINSTANCE)
		compilationHelper.javaVersion = JavaVersion::JAVA8
	}

	@Test
	def void testInvalidEcore() {
		'''
			behavior test
			import ecore "data/metamodels/404.ecore"
		'''.parse.ecoreImport.assertError(
			AlePackage.Literals::ECORE_IMPORT,
			AleValidator::SYNTAX_NOT_FOUND
		)
	}

	@Test
	def void testOpenExistingClass() {
		'''
			behavior test
			import ecore "data/metamodels/BoolExp.ecore"
			open class And {}
		'''.parse.assertNoIssues
	}

	@Test
	def void testOpenUnknownClass() {
		'''
			behavior test
			import ecore "data/metamodels/BoolExp.ecore"
			open class A {}
		'''.parse.assertError(
			AlePackage.Literals::ALE_CLASS,
			AleValidator::UNKNOWN_OPENCLASS
		)
	}
}
