<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="prodSys" nsURI="http://www.example.org/prodSys" nsPrefix="prodSys">
  <eClassifiers xsi:type="ecore:EClass" name="Machine">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ref" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inC" upperBound="-1" eType="#//Conveyor"
        eOpposite="#//Conveyor/outM"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outC" upperBound="-1" eType="#//Conveyor"
        eOpposite="#//Conveyor/inM"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Conveyor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="outM" eType="#//Machine"
        eOpposite="#//Machine/inC"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inM" eType="#//Machine"
        eOpposite="#//Machine/outC"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parts" upperBound="-1"
        eType="#//Part" containment="true" eOpposite="#//Part/owner"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Part">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="creationTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner" eType="#//Conveyor"
        eOpposite="#//Conveyor/parts"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Root">
    <eStructuralFeatures xsi:type="ecore:EReference" name="machine" upperBound="-1"
        eType="#//Machine" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="conveyor" upperBound="-1"
        eType="#//Conveyor" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
