package exec_iot_lua.revisitor.operations.exec_iot_lua;

import activitydiagram_exec.revisitor.operations.activitydiagram_exec.ActivityEdgeOperation;
import activitydiagram_exec.revisitor.operations.activitydiagram_exec.NamedActivityOperation;

@SuppressWarnings("all")
public interface ControlFlowOperation extends activitydiagram_exec.revisitor.operations.activitydiagram_exec.ControlFlowOperation, ActivityEdgeOperation, exec_iot_lua.revisitor.operations.exec_iot_lua.ActivityEdgeOperation, NamedActivityOperation, exec_iot_lua.revisitor.operations.exec_iot_lua.NamedActivityOperation {
}
