package exec_iot_lua.revisitor.operations.exec_iot_lua;

import activitydiagram_exec.revisitor.operations.activitydiagram_exec.ActivityNodeOperation;
import activitydiagram_exec.revisitor.operations.activitydiagram_exec.NamedActivityOperation;

@SuppressWarnings("all")
public interface ExecutableNodeOperation extends activitydiagram_exec.revisitor.operations.activitydiagram_exec.ExecutableNodeOperation, ActivityNodeOperation, exec_iot_lua.revisitor.operations.exec_iot_lua.ActivityNodeOperation, NamedActivityOperation, exec_iot_lua.revisitor.operations.exec_iot_lua.NamedActivityOperation {
}
