package exec_iot_lua.revisitor.operations.exec_iot_lua;

import lua_exec.revisitor.operations.lua_exec.ExpressionOperation;
import lua_exec.revisitor.operations.lua_exec.StatementOperation;
import lua_exec.revisitor.operations.lua_exec.Statement_FunctioncallOrAssignmentOperation;

@SuppressWarnings("all")
public interface Expression_FunctionOperation extends lua_exec.revisitor.operations.lua_exec.Expression_FunctionOperation, ExpressionOperation, exec_iot_lua.revisitor.operations.exec_iot_lua.ExpressionOperation, Statement_FunctioncallOrAssignmentOperation, exec_iot_lua.revisitor.operations.exec_iot_lua.Statement_FunctioncallOrAssignmentOperation, StatementOperation, exec_iot_lua.revisitor.operations.exec_iot_lua.StatementOperation {
}
