package exec_iot_lua.revisitor.operations.exec_iot_lua;

import exec_iot_lua.revisitor.operations.exec_iot_lua.ExpressionOperation;
import exec_iot_lua.revisitor.operations.exec_iot_lua.StatementOperation;
import exec_iot_lua.revisitor.operations.exec_iot_lua.Statement_FunctioncallOrAssignmentOperation;

@SuppressWarnings("all")
public interface Expression_CallMemberFunctionOperation extends lua_exec.revisitor.operations.lua_exec.Expression_CallMemberFunctionOperation, ExpressionOperation, lua_exec.revisitor.operations.lua_exec.ExpressionOperation, Statement_FunctioncallOrAssignmentOperation, lua_exec.revisitor.operations.lua_exec.Statement_FunctioncallOrAssignmentOperation, StatementOperation, lua_exec.revisitor.operations.lua_exec.StatementOperation {
}
