package exec_iot_lua.revisitor.operations.exec_iot_lua;

import exec_iot_lua.revisitor.operations.exec_iot_lua.LastStatementOperation;
import exec_iot_lua.revisitor.operations.exec_iot_lua.LastStatement_ReturnOperation;

@SuppressWarnings("all")
public interface LastStatement_ReturnWithValueOperation extends lua_exec.revisitor.operations.lua_exec.LastStatement_ReturnWithValueOperation, LastStatement_ReturnOperation, lua_exec.revisitor.operations.lua_exec.LastStatement_ReturnOperation, LastStatementOperation, lua_exec.revisitor.operations.lua_exec.LastStatementOperation {
}
