package exec_iot_lua.revisitor.operations.exec_iot_lua;

import lua_exec.revisitor.operations.lua_exec.LastStatementOperation;
import lua_exec.revisitor.operations.lua_exec.LastStatement_ReturnOperation;

@SuppressWarnings("all")
public interface LastStatement_ReturnWithValueOperation extends lua_exec.revisitor.operations.lua_exec.LastStatement_ReturnWithValueOperation, LastStatement_ReturnOperation, exec_iot_lua.revisitor.operations.exec_iot_lua.LastStatement_ReturnOperation, LastStatementOperation, exec_iot_lua.revisitor.operations.exec_iot_lua.LastStatementOperation {
}
