package exec_iot_lua.revisitor.operations.exec_iot_lua;

import exec_iot_lua.revisitor.operations.exec_iot_lua.ActivityNodeOperation;
import exec_iot_lua.revisitor.operations.exec_iot_lua.ControlNodeOperation;
import exec_iot_lua.revisitor.operations.exec_iot_lua.NamedActivityOperation;

@SuppressWarnings("all")
public interface MergeNodeOperation extends activitydiagram_exec.revisitor.operations.activitydiagram_exec.MergeNodeOperation, ControlNodeOperation, activitydiagram_exec.revisitor.operations.activitydiagram_exec.ControlNodeOperation, ActivityNodeOperation, activitydiagram_exec.revisitor.operations.activitydiagram_exec.ActivityNodeOperation, NamedActivityOperation, activitydiagram_exec.revisitor.operations.activitydiagram_exec.NamedActivityOperation {
}
