package exec_iot_lua.revisitor.operations.exec_iot_lua;

import activitydiagram_exec.revisitor.operations.activitydiagram_exec.ActionOperation;
import activitydiagram_exec.revisitor.operations.activitydiagram_exec.ActivityNodeOperation;
import activitydiagram_exec.revisitor.operations.activitydiagram_exec.ExecutableNodeOperation;
import activitydiagram_exec.revisitor.operations.activitydiagram_exec.NamedActivityOperation;

@SuppressWarnings("all")
public interface OpaqueActionOperation extends activitydiagram_exec.revisitor.operations.activitydiagram_exec.OpaqueActionOperation, ActionOperation, exec_iot_lua.revisitor.operations.exec_iot_lua.ActionOperation, ExecutableNodeOperation, exec_iot_lua.revisitor.operations.exec_iot_lua.ExecutableNodeOperation, ActivityNodeOperation, exec_iot_lua.revisitor.operations.exec_iot_lua.ActivityNodeOperation, NamedActivityOperation, exec_iot_lua.revisitor.operations.exec_iot_lua.NamedActivityOperation {
}
