package exec_iot_lua.revisitor.operations.exec_iot_lua;

import lua_exec.revisitor.operations.lua_exec.StatementOperation;
import lua_exec.revisitor.operations.lua_exec.Statement_FunctioncallOrAssignmentOperation;

@SuppressWarnings("all")
public interface Statement_CallFunctionOperation extends lua_exec.revisitor.operations.lua_exec.Statement_CallFunctionOperation, Statement_FunctioncallOrAssignmentOperation, exec_iot_lua.revisitor.operations.exec_iot_lua.Statement_FunctioncallOrAssignmentOperation, StatementOperation, exec_iot_lua.revisitor.operations.exec_iot_lua.StatementOperation {
}
