package activitydiagram_simpleexpressions_exec.revisitor.operations.activitydiagram_simpleexpressions_exec;

import activitydiagram_exec.revisitor.operations.activitydiagram_exec.NamedActivityOperation;

@SuppressWarnings("all")
public interface ActivityNodeOperation extends activitydiagram_exec.revisitor.operations.activitydiagram_exec.ActivityNodeOperation, NamedActivityOperation, activitydiagram_simpleexpressions_exec.revisitor.operations.activitydiagram_simpleexpressions_exec.NamedActivityOperation {
}
