package activitydiagram_simpleexpressions_exec.revisitor.operations.activitydiagram_simpleexpressions_exec;

@SuppressWarnings("all")
public interface ContextOperation extends activitydiagram_exec.revisitor.operations.activitydiagram_exec.ContextOperation {
}
