package activitydiagram_simpleexpressions_exec.revisitor.operations.activitydiagram_simpleexpressions_exec;

import activitydiagram_exec.revisitor.operations.activitydiagram_exec.TokenOperation;

@SuppressWarnings("all")
public interface ForkedTokenOperation extends activitydiagram_exec.revisitor.operations.activitydiagram_exec.ForkedTokenOperation, TokenOperation, activitydiagram_simpleexpressions_exec.revisitor.operations.activitydiagram_simpleexpressions_exec.TokenOperation {
}
