package activitydiagram_simpleexpressions_exec.revisitor.operations.activitydiagram_simpleexpressions_exec;

import activitydiagram_exec.revisitor.operations.activitydiagram_exec.ValueOperation;

@SuppressWarnings("all")
public interface IntegerValueOperation extends activitydiagram_exec.revisitor.operations.activitydiagram_exec.IntegerValueOperation, ValueOperation, activitydiagram_simpleexpressions_exec.revisitor.operations.activitydiagram_simpleexpressions_exec.ValueOperation {
}
