package activitydiagram_simpleexpressions_exec.revisitor.operations.activitydiagram_simpleexpressions_exec;

@SuppressWarnings("all")
public interface NamedActivityOperation extends activitydiagram_exec.revisitor.operations.activitydiagram_exec.NamedActivityOperation {
}
