package activitydiagram_simpleexpressions_exec.revisitor.operations.activitydiagram_simpleexpressions_exec;

import activitydiagram_simpleexpressions_exec.revisitor.operations.activitydiagram_simpleexpressions_exec.SEExpressionOperation;
import activitydiagram_simpleexpressions_exec.revisitor.operations.activitydiagram_simpleexpressions_exec.SEVariableOperation;

@SuppressWarnings("all")
public interface SEBooleanVariableOperation extends simpleexpressions_exec.revisitor.operations.simpleexpressions_exec.SEBooleanVariableOperation, SEVariableOperation, simpleexpressions_exec.revisitor.operations.simpleexpressions_exec.SEVariableOperation, SEExpressionOperation, simpleexpressions_exec.revisitor.operations.simpleexpressions_exec.SEExpressionOperation {
}
