package activitydiagram_simpleexpressions_exec.revisitor.operations.activitydiagram_simpleexpressions_exec;

@SuppressWarnings("all")
public interface SEExpressionOperation extends simpleexpressions_exec.revisitor.operations.simpleexpressions_exec.SEExpressionOperation {
}
