package activitydiagram_simpleexpressions_exec.revisitor.operations.activitydiagram_simpleexpressions_exec;

import activitydiagram_simpleexpressions_exec.revisitor.operations.activitydiagram_simpleexpressions_exec.SEExpressionOperation;
import activitydiagram_simpleexpressions_exec.revisitor.operations.activitydiagram_simpleexpressions_exec.SEValueOperation;

@SuppressWarnings("all")
public interface SEIntegerValueOperation extends simpleexpressions_exec.revisitor.operations.simpleexpressions_exec.SEIntegerValueOperation, SEValueOperation, simpleexpressions_exec.revisitor.operations.simpleexpressions_exec.SEValueOperation, SEExpressionOperation, simpleexpressions_exec.revisitor.operations.simpleexpressions_exec.SEExpressionOperation {
}
