package activitydiagram_simpleexpressions_exec.revisitor.operations.activitydiagram_simpleexpressions_exec;

@SuppressWarnings("all")
public interface VariableOperation extends activitydiagram_exec.revisitor.operations.activitydiagram_exec.VariableOperation {
}
