package iot_simpleexpression_exec.revisitor.operations.iot_simpleexpression_exec;

import iot_simpleexpression_exec.revisitor.operations.iot_simpleexpression_exec.NamedActivityOperation;

@SuppressWarnings("all")
public interface ActivityEdgeOperation extends activitydiagram_exec.revisitor.operations.activitydiagram_exec.ActivityEdgeOperation, NamedActivityOperation, activitydiagram_exec.revisitor.operations.activitydiagram_exec.NamedActivityOperation {
}
