package iot_simpleexpression_exec.revisitor.operations.iot_simpleexpression_exec;

import activitydiagram_exec.revisitor.operations.activitydiagram_exec.NamedActivityOperation;

@SuppressWarnings("all")
public interface ActivityNodeOperation extends activitydiagram_exec.revisitor.operations.activitydiagram_exec.ActivityNodeOperation, NamedActivityOperation, iot_simpleexpression_exec.revisitor.operations.iot_simpleexpression_exec.NamedActivityOperation {
}
