package iot_simpleexpression_exec.revisitor.operations.iot_simpleexpression_exec;

import evalsimpleal.revisitor.operations.evalsimpleal.ArithOpOperation;
import evalsimpleal.revisitor.operations.evalsimpleal.ArithOperation;

@SuppressWarnings("all")
public interface ArithMinusOperation extends evalsimpleal.revisitor.operations.evalsimpleal.ArithMinusOperation, ArithOpOperation, iot_simpleexpression_exec.revisitor.operations.iot_simpleexpression_exec.ArithOpOperation, ArithOperation, iot_simpleexpression_exec.revisitor.operations.iot_simpleexpression_exec.ArithOperation {
}
