package iot_simpleexpression_exec.revisitor.operations.iot_simpleexpression_exec;

import activitydiagram_exec.revisitor.operations.activitydiagram_exec.ValueOperation;

@SuppressWarnings("all")
public interface BooleanValueOperation extends activitydiagram_exec.revisitor.operations.activitydiagram_exec.BooleanValueOperation, ValueOperation, iot_simpleexpression_exec.revisitor.operations.iot_simpleexpression_exec.ValueOperation {
}
