package iot_simpleexpression_exec.revisitor.operations.iot_simpleexpression_exec;

import activitydiagram_exec.revisitor.operations.activitydiagram_exec.VariableOperation;

@SuppressWarnings("all")
public interface BooleanVariableOperation extends activitydiagram_exec.revisitor.operations.activitydiagram_exec.BooleanVariableOperation, VariableOperation, iot_simpleexpression_exec.revisitor.operations.iot_simpleexpression_exec.VariableOperation {
}
