package iot_simpleexpression_exec.revisitor.operations.iot_simpleexpression_exec;

import activitydiagram_exec.revisitor.operations.activitydiagram_exec.TokenOperation;

@SuppressWarnings("all")
public interface ControlTokenOperation extends activitydiagram_exec.revisitor.operations.activitydiagram_exec.ControlTokenOperation, TokenOperation, iot_simpleexpression_exec.revisitor.operations.iot_simpleexpression_exec.TokenOperation {
}
