package iot_simpleexpression_exec.revisitor.operations.iot_simpleexpression_exec;

import iot_simpleexpression_exec.revisitor.operations.iot_simpleexpression_exec.ContainedOperation;
import iot_simpleexpression_exec.revisitor.operations.iot_simpleexpression_exec.NamedElementOperation;

@SuppressWarnings("all")
public interface ExceptionDefOperation extends ContainedOperation, NamedElementOperation {
}
