package iot_simpleexpression_exec.revisitor.operations.iot_simpleexpression_exec;

import iot_simpleexpression_exec.revisitor.operations.iot_simpleexpression_exec.ActivityNodeOperation;
import iot_simpleexpression_exec.revisitor.operations.iot_simpleexpression_exec.NamedActivityOperation;

@SuppressWarnings("all")
public interface ExecutableNodeOperation extends activitydiagram_exec.revisitor.operations.activitydiagram_exec.ExecutableNodeOperation, ActivityNodeOperation, activitydiagram_exec.revisitor.operations.activitydiagram_exec.ActivityNodeOperation, NamedActivityOperation, activitydiagram_exec.revisitor.operations.activitydiagram_exec.NamedActivityOperation {
}
