package iot_simpleexpression_exec.revisitor.operations.iot_simpleexpression_exec;

import activitydiagram_exec.revisitor.operations.activitydiagram_exec.ActivityNodeOperation;
import activitydiagram_exec.revisitor.operations.activitydiagram_exec.ControlNodeOperation;
import activitydiagram_exec.revisitor.operations.activitydiagram_exec.NamedActivityOperation;

@SuppressWarnings("all")
public interface FinalNodeOperation extends activitydiagram_exec.revisitor.operations.activitydiagram_exec.FinalNodeOperation, ControlNodeOperation, iot_simpleexpression_exec.revisitor.operations.iot_simpleexpression_exec.ControlNodeOperation, ActivityNodeOperation, iot_simpleexpression_exec.revisitor.operations.iot_simpleexpression_exec.ActivityNodeOperation, NamedActivityOperation, iot_simpleexpression_exec.revisitor.operations.iot_simpleexpression_exec.NamedActivityOperation {
}
