package iot_simpleexpression_exec.revisitor.operations.iot_simpleexpression_exec;

import iot_simpleexpression_exec.revisitor.operations.iot_simpleexpression_exec.TokenOperation;

@SuppressWarnings("all")
public interface ForkedTokenOperation extends activitydiagram_exec.revisitor.operations.activitydiagram_exec.ForkedTokenOperation, TokenOperation, activitydiagram_exec.revisitor.operations.activitydiagram_exec.TokenOperation {
}
