package iot_simpleexpression_exec.revisitor.operations.iot_simpleexpression_exec;

import iot_simpleexpression_exec.revisitor.operations.iot_simpleexpression_exec.ValueOperation;

@SuppressWarnings("all")
public interface IntegerValueOperation extends activitydiagram_exec.revisitor.operations.activitydiagram_exec.IntegerValueOperation, ValueOperation, activitydiagram_exec.revisitor.operations.activitydiagram_exec.ValueOperation {
}
