package iot_simpleexpression_exec.revisitor.operations.iot_simpleexpression_exec;

import simpleexpressions_exec.revisitor.operations.simpleexpressions_exec.SEExpressionOperation;
import simpleexpressions_exec.revisitor.operations.simpleexpressions_exec.SEValueOperation;

@SuppressWarnings("all")
public interface SEIntegerValueOperation extends simpleexpressions_exec.revisitor.operations.simpleexpressions_exec.SEIntegerValueOperation, SEValueOperation, iot_simpleexpression_exec.revisitor.operations.iot_simpleexpression_exec.SEValueOperation, SEExpressionOperation, iot_simpleexpression_exec.revisitor.operations.iot_simpleexpression_exec.SEExpressionOperation {
}
