package iot_simpleexpression_exec.revisitor.operations.iot_simpleexpression_exec;

import iot_simpleexpression_exec.revisitor.operations.iot_simpleexpression_exec.SEExpressionOperation;
import iot_simpleexpression_exec.revisitor.operations.iot_simpleexpression_exec.SEVariableOperation;

@SuppressWarnings("all")
public interface SEIntegerVariableOperation extends simpleexpressions_exec.revisitor.operations.simpleexpressions_exec.SEIntegerVariableOperation, SEVariableOperation, simpleexpressions_exec.revisitor.operations.simpleexpressions_exec.SEVariableOperation, SEExpressionOperation, simpleexpressions_exec.revisitor.operations.simpleexpressions_exec.SEExpressionOperation {
}
