package iot_simpleexpression_exec.revisitor.operations.iot_simpleexpression_exec;

import simpleexpressions_exec.revisitor.operations.simpleexpressions_exec.SEExpressionOperation;
import simpleexpressions_exec.revisitor.operations.simpleexpressions_exec.SEIntegerExpressionOperation;

@SuppressWarnings("all")
public interface SEIntegerComparisonExpressionOperation extends simpleexpressions_exec.revisitor.operations.simpleexpressions_exec.SEIntegerComparisonExpressionOperation, SEIntegerExpressionOperation, iot_simpleexpression_exec.revisitor.operations.iot_simpleexpression_exec.SEIntegerExpressionOperation, SEExpressionOperation, iot_simpleexpression_exec.revisitor.operations.iot_simpleexpression_exec.SEExpressionOperation {
}
