package iot_simpleexpression_exec.revisitor.operations.iot_simpleexpression_exec;

import simpleexpressions_exec.revisitor.operations.simpleexpressions_exec.SEExpressionOperation;

@SuppressWarnings("all")
public interface SEVariableOperation extends simpleexpressions_exec.revisitor.operations.simpleexpressions_exec.SEVariableOperation, SEExpressionOperation, iot_simpleexpression_exec.revisitor.operations.iot_simpleexpression_exec.SEExpressionOperation {
}
