/*
 * generated by Xtext 2.12.0
 */
package iot.simpleexpressions.xtext.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractIoTValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.example.org/iot"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.example.org/model"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://idlmm/1.0"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.example.org/simpleALEnv"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://activitydiagram/1.0"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.example.org/simpleexpressions"));
		return result;
	}
	
}
