/**
 * generated by Xtext 2.14.0
 */
package ale.xtext.ale.impl;

import ale.xtext.ale.AlePackage;
import ale.xtext.ale.OverrideMethod;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Override Method</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class OverrideMethodImpl extends ConcreteMethodImpl implements OverrideMethod
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected OverrideMethodImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AlePackage.Literals.OVERRIDE_METHOD;
  }

} //OverrideMethodImpl
