/**
 * generated by Xtext 2.14.0
 */
package ale.xtext.ale;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Override Method</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see ale.xtext.ale.AlePackage#getOverrideMethod()
 * @model
 * @generated
 */
public interface OverrideMethod extends ConcreteMethod
{
} // OverrideMethod
