/**
 * generated by Xtext 2.10.0
 */
package ale.xtext.ale;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Def Method</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see ale.xtext.ale.AlePackage#getDefMethod()
 * @model
 * @generated
 */
public interface DefMethod extends ConcreteMethod
{
} // DefMethod
