/**
 * generated by Xtext 2.10.0
 */
package ale.xtext.ale;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see ale.xtext.ale.AlePackage#getExpression()
 * @model
 * @generated
 */
public interface Expression extends Statement
{
} // Expression
