/**
 * generated by Xtext 2.12.0
 */
package ale.xtext.ale;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Import Ecore</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ale.xtext.ale.ImportEcore#getRef <em>Ref</em>}</li>
 * </ul>
 *
 * @see ale.xtext.ale.AlePackage#getImportEcore()
 * @model
 * @generated
 */
public interface ImportEcore extends EObject
{
  /**
   * Returns the value of the '<em><b>Ref</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ref</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ref</em>' attribute.
   * @see #setRef(String)
   * @see ale.xtext.ale.AlePackage#getImportEcore_Ref()
   * @model
   * @generated
   */
  String getRef();

  /**
   * Sets the value of the '{@link ale.xtext.ale.ImportEcore#getRef <em>Ref</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ref</em>' attribute.
   * @see #getRef()
   * @generated
   */
  void setRef(String value);

} // ImportEcore
