/**
 * generated by Xtext 2.10.0
 */
package ale.xtext.ale;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Int Type T</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see ale.xtext.ale.AlePackage#getIntTypeT()
 * @model
 * @generated
 */
public interface IntTypeT extends TypeSystem
{
} // IntTypeT
