/**
 * generated by Xtext 2.10.0
 */
package ale.xtext.ale;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Return Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ale.xtext.ale.ReturnStatement#getReturned <em>Returned</em>}</li>
 * </ul>
 *
 * @see ale.xtext.ale.AlePackage#getReturnStatement()
 * @model
 * @generated
 */
public interface ReturnStatement extends Statement
{
  /**
   * Returns the value of the '<em><b>Returned</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Returned</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Returned</em>' containment reference.
   * @see #setReturned(Expression)
   * @see ale.xtext.ale.AlePackage#getReturnStatement_Returned()
   * @model containment="true"
   * @generated
   */
  Expression getReturned();

  /**
   * Sets the value of the '{@link ale.xtext.ale.ReturnStatement#getReturned <em>Returned</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Returned</em>' containment reference.
   * @see #getReturned()
   * @generated
   */
  void setReturned(Expression value);

} // ReturnStatement
