/**
 * generated by Xtext 2.10.0
 */
package ale.xtext.ale;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Self Ref</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see ale.xtext.ale.AlePackage#getSelfRef()
 * @model
 * @generated
 */
public interface SelfRef extends Expression
{
} // SelfRef
