/**
 * generated by Xtext 2.10.0
 */
package ale.xtext.ale;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>While Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ale.xtext.ale.WhileStatement#getCondition <em>Condition</em>}</li>
 *   <li>{@link ale.xtext.ale.WhileStatement#getWhileBlock <em>While Block</em>}</li>
 * </ul>
 *
 * @see ale.xtext.ale.AlePackage#getWhileStatement()
 * @model
 * @generated
 */
public interface WhileStatement extends Statement
{
  /**
   * Returns the value of the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Condition</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condition</em>' containment reference.
   * @see #setCondition(Expression)
   * @see ale.xtext.ale.AlePackage#getWhileStatement_Condition()
   * @model containment="true"
   * @generated
   */
  Expression getCondition();

  /**
   * Sets the value of the '{@link ale.xtext.ale.WhileStatement#getCondition <em>Condition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Condition</em>' containment reference.
   * @see #getCondition()
   * @generated
   */
  void setCondition(Expression value);

  /**
   * Returns the value of the '<em><b>While Block</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>While Block</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>While Block</em>' containment reference.
   * @see #setWhileBlock(Block)
   * @see ale.xtext.ale.AlePackage#getWhileStatement_WhileBlock()
   * @model containment="true"
   * @generated
   */
  Block getWhileBlock();

  /**
   * Sets the value of the '{@link ale.xtext.ale.WhileStatement#getWhileBlock <em>While Block</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>While Block</em>' containment reference.
   * @see #getWhileBlock()
   * @generated
   */
  void setWhileBlock(Block value);

} // WhileStatement
