/*
 * generated by Xtext 2.12.0
 */
package brew.xtext.scoping;

import org.eclipse.xtext.xbase.scoping.batch.XbaseBatchScopeProvider;

public abstract class AbstractBrewScopeProvider extends XbaseBatchScopeProvider {
}
