<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="iot_lua" nsURI="http://www.example.org/iot_lua" nsPrefix="iot_lua">
  <eClassifiers xsi:type="ecore:EClass" name="ExpressionBindStatement" eSuperTypes="../../org.xtext.activitydiagram.model/model/activitydiagram.ecore#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="delegate" eType="ecore:EClass ../../org.xtext.lua/model/generated/Lua.ecore#//Statement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValueBindExpression" eSuperTypes="../../org.xtext.activitydiagram.model/model/activitydiagram.ecore#//Value">
    <eStructuralFeatures xsi:type="ecore:EReference" name="delegate" eType="ecore:EClass ../../org.xtext.lua/model/generated/Lua.ecore#//Expression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanValueBindExpression" eSuperTypes="../../org.xtext.activitydiagram.model/model/activitydiagram.ecore#//BooleanValue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="delegate" eType="ecore:EClass ../../org.xtext.lua/model/generated/Lua.ecore#//Expression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanVariableBindStatement_Assignment"
      eSuperTypes="../../org.xtext.activitydiagram.model/model/activitydiagram.ecore#//BooleanVariable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="delegate" eType="ecore:EClass ../../org.xtext.lua/model/generated/Lua.ecore#//Statement_Assignment"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerVariableBindStatement_Assignment"
      eSuperTypes="../../org.xtext.activitydiagram.model/model/activitydiagram.ecore#//IntegerVariable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="delegate" eType="ecore:EClass ../../org.xtext.lua/model/generated/Lua.ecore#//Statement_Assignment"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerValueBindExpression_Number" eSuperTypes="../../org.xtext.activitydiagram.model/model/activitydiagram.ecore#//IntegerValue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="delegate" eType="ecore:EClass ../../org.xtext.lua/model/generated/Lua.ecore#//Expression_Number"/>
  </eClassifiers>
</ecore:EPackage>
