package modularactivitydiagram.revisitor.operations;

public interface BooleanBinaryExpression_AspectOperation extends modularactivitydiagram.revisitor.operations.BooleanExpression_AspectOperation, modularactivitydiagram.revisitor.operations.BooleanBinaryExpressionOperation {
	void execute();
}
