package modularactivitydiagram.revisitor.operations;

public interface IntegerCalculationExpression_AspectOperation extends modularactivitydiagram.revisitor.operations.IntegerCalculationExpressionOperation, modularactivitydiagram.revisitor.operations.IntegerExpression_AspectOperation {
	void execute();
}
