package modularactivitydiagram.revisitor.operations;

public interface IntegerComparisonExpression_AspectOperation extends modularactivitydiagram.revisitor.operations.IntegerComparisonExpressionOperation, modularactivitydiagram.revisitor.operations.IntegerExpression_AspectOperation {
	void execute();
}
