/*
 * generated by Xtext 2.12.0
 */
package iot.lua.xtext.tests

import com.google.inject.Inject
import com.google.inject.Provider
import iot.System
import org.eclipse.emf.common.util.URI
import org.eclipse.emf.ecore.resource.ResourceSet
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Test
import org.junit.runner.RunWith
import org.junit.Assert

@RunWith(XtextRunner)
@InjectWith(IotLuaXtextInjectorProvider)
class IotLuaXtextPerfsTest {

	@Inject
	Provider<ResourceSet> rsp

	
	@Test
	def void loadModelMergeFork() {

		val rs = rsp.get
		val r = rs.getResource(URI.createURI("perfs1.iot"), true)
		r.load(null)

		val s = r.contents.head as System

		 val xmiResource = rs.createResource(URI.createURI("perfs1.xmi"));
		 
		  xmiResource.getContents().add(s);
		  xmiResource.save(null)
	}
}
