/*
 * generated by Xtext 2.12.0
 */
package ale.xtext.scoping;

import org.eclipse.xtext.xbase.scoping.batch.XbaseBatchScopeProvider;

public abstract class AbstractAleScopeProvider extends XbaseBatchScopeProvider {
}
