/**
 * generated by Xtext 2.10.0
 */
package ale.xtext.ui;

import ale.xtext.ui.AbstractAleUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class AleUiModule extends AbstractAleUiModule {
  public AleUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
