/*
 * generated by Xtext 2.12.0
 */
package ale.xtext.ide

import ale.xtext.AleRuntimeModule
import ale.xtext.AleStandaloneSetup
import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class AleIdeSetup extends AleStandaloneSetup {

	override createInjector() {
		return Guice.createInjector(Modules2.mixin(new AleRuntimeModule, new AleIdeModule))
	}
	
}
