<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="hierarchicalFsmEnv" nsURI="http://www.example.org/hierarchicalFsmEnv"
    nsPrefix="hierarchicalFsmEnv">
  <eClassifiers xsi:type="ecore:EClass" name="CompositeState" eSuperTypes="../../BasicFsmEnv/model/basicFsmEnv.ecore#//State">
    <eStructuralFeatures xsi:type="ecore:EReference" name="regions" lowerBound="1"
        upperBound="-1" eType="#//Region" containment="true" eOpposite="#//Region/parent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Region">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//CompositeState" eOpposite="#//CompositeState/regions"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="states" upperBound="-1"
        eType="ecore:EClass ../../BasicFsmEnv/model/basicFsmEnv.ecore#//State" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
