<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="tokenHolder" nsURI="http://www.example.org/tokenHolder" nsPrefix="tokenHolder">
  <eClassifiers xsi:type="ecore:EClass" name="H" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tokens" upperBound="-1"
        eType="#//T" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="T" abstract="true" interface="true">
    <eAnnotations source="@Required"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="P" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inHolders" upperBound="-1"
        eType="#//H"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outHolders" upperBound="-1"
        eType="#//H"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="R" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="h" upperBound="-1" eType="#//H"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="p" upperBound="-1" eType="#//P"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
