<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="minifsm" nsURI="http://minifsm/" nsPrefix="minifsm">
  <eClassifiers xsi:type="ecore:EClass" name="Machine">
    <eStructuralFeatures xsi:type="ecore:EReference" name="states" upperBound="-1" eType="//State" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transitions" upperBound="-1" eType="//Transition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="State">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="out" upperBound="-1" eType="//Transition" eOpposite="//Transition/src"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="in" upperBound="-1" eType="//Transition" eOpposite="//Transition/tgt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="event">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EChar"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="src" eType="//State" eOpposite="//State/out"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tgt" eType="//State" eOpposite="//State/in"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FinalState" eSuperTypes="//State"/>
</ecore:EPackage>
